<a href="https://colab.research.google.com/github/karunakar-Nridegree/NUMPY/blob/main/NUMPY_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])

In [ ]:
type(arr)

numpy.ndarray

In [4]:
arr1 = np.random.randint(1,2,(3,1))

In [6]:
arr.shape
arr1.shape

(3, 1)

In [7]:
arr.size

6

In [8]:
result = np.dot(arr,arr1)

In [9]:
print(result)

[[ 6]
 [15]]


In [15]:
r1 = np.random.randint(10,20,(3,3))
print(r1)

[[18 10 19]
 [15 14 18]
 [12 16 15]]


In [17]:
r1 = np.eye(3)
print(r1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
r2 = np.eye(4)
print(r2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [33]:
r2 = np.eye(3) # Changed to (3,3) to match the dimensions of r1
result2 = np.dot(r1, r2)
print(result2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [34]:
# M.I.= I.M = M

In [35]:
# Mathematical Operations
# + - * /
t1 = np.random.randint(3,6,(3,3))
t2 = np.random.randint(2,6,(3,3))

In [36]:
print(t1)
print(t2)

[[3 4 4]
 [4 4 5]
 [3 5 5]]
[[5 2 2]
 [4 3 2]
 [3 2 3]]


In [37]:
t3 = t1 + t2

In [38]:
print(t3)

[[8 6 6]
 [8 7 7]
 [6 7 8]]


In [39]:
# Matrix multiplication
result = np.dot(arr,arr1)

In [44]:
# Statistical operations
mean = t3.mean()
max = t3.max()
median = np.median(t3)
std = np.std(t3)
var = np.var(t3)

In [45]:
print(mean)
print(max)
print(median)
print(std)
print(var)

7.0
8
7.0
0.816496580927726
0.6666666666666666


In [46]:
std * std

0.6666666666666666

In [47]:
# Trignometric functions
# sin(x)
# cos(x)
# Tan(x) - sin(x) / cos(x)
# cosec -
# sec - 1 / cos(x)
# cot - 1 / tan(x)
angles = np.array([0,15,30,45,60,75,90])
result = np.sin(np.radians(angles))
result1 = np.cos(np.radians(angles))
result2 = np.tan(np.radians(angles))

In [48]:
print(result)
print(result1)
print(result2)

[0.         0.25881905 0.5        0.70710678 0.8660254  0.96592583
 1.        ]
[1.00000000e+00 9.65925826e-01 8.66025404e-01 7.07106781e-01
 5.00000000e-01 2.58819045e-01 6.12323400e-17]
[0.00000000e+00 2.67949192e-01 5.77350269e-01 1.00000000e+00
 1.73205081e+00 3.73205081e+00 1.63312394e+16]


In [53]:
arr = np.array([[1,1,2,4,5,6]])
# Reshpa the array
reshapedarr = arr.reshape(3,2)
print(reshapedarr)
# Convert / arr.flatten any n dim array
flattendarr = arr.flatten()
print(flattendarr)

[[1 1]
 [2 4]
 [5 6]]
[1 1 2 4 5 6]


In [54]:
# Stacking the data
arr1 = np.array([[1,2,3,4],[2,3,4,5]])
arr2 = np.array([10,20,30,40])

arr3 = np.vstack((arr1,arr2))
print(f'The shape of arr3 is {arr3.shape}')

# Horizantal Stacking
arr4 = np.hstack((arr1,arr2.reshape(2,2)))
print(f'The shape of arr4 is {arr4.shape}')
print(arr4)

The shape of arr3 is (3, 4)
The shape of arr4 is (2, 6)
[[ 1  2  3  4 10 20]
 [ 2  3  4  5 30 40]]


In [61]:
# Filtering
arr = np.array([10,20,30,40,50,60,70,80])

farr = arr [arr > 40]

print(farr)

[50 60 70 80]
