<a href="https://colab.research.google.com/github/karunakar-Nridegree/NUMPY/blob/main/Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
#Numpy - Numeric python
#most powerful package library
#Numpy Dimensions


#A - One Dimensional Array
#[A,B] ||[A
#         B ] Two Dimensional array row ||column
#three Dimensional
#Array - storing ,manipulating,similar data type
#faster than any mathematical functions
#convinient compared to other package
# memory efficiency
# support multi dimensional arrays



# speed(numpy operations) > speed (lists operations)
# size(numpy operations) > size (lists operations)
# memory Optimization (numpy) > memory Optimization (list operations)

In [31]:
# Install numpy - pip3 install numpy // pip install numpy

In [1]:
import numpy as np

In [3]:
arr1D = np.array([1,2,3,4,5])
print(arr1D)

[1 2 3 4 5]


In [4]:
arr2D = np.array([[1,2,3],[4,5,5]])
print(arr2D)

[[1 2 3]
 [4 5 5]]


In [12]:
#default values
allzero = np.zeros((2,3))
print(allzero)

#default values
allones = np.ones((2,3))
print(allones)


#default values
allconstant = np.full((2,3),6)
print(allconstant)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[6 6 6]
 [6 6 6]]


In [14]:
# create an identity matrix - I square matrix
identity = np.eye(4)
print(identity)

#Identity matrix - Aii = 1 && Aij = 0
#For all A Belongs to R MxN
# Aij-

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [20]:
#crateing random matrices
 # with 0 to 1
rand1 = np.random.rand(3,3)
print(rand1)


# between a and b
rand2 = np.random.randint(10,20,(3,3))
print(rand2)

[[0.99415842 0.1445596  0.54061559]
 [0.24597317 0.75881651 0.63103307]
 [0.4401671  0.80810151 0.78525629]]
[[10 14 18]
 [16 12 18]
 [16 17 16]]


In [25]:
#Array properties

arr = np.array([[1,2,3,4],[2,3,4,5]])
print(arr)

#Shape or array
print(f'shape of the array is {arr.shape}')

#Size of array
print(f'size of the array is {arr.size}')

#Datatype of array
print(f'Data type of the array is {arr.dtype}')

#Dimensions of array
print(f'The Dimension of the array is {arr.ndim}')

[[1 2 3 4]
 [2 3 4 5]]
shape of the array is (2, 4)
size of the array is 8
Data type of the array is int64
The Dimension of the array is 2


In [30]:
# Indexing and sliding
# Access the elements in 1D array

arr = np.array([1,2,3,4])
print(arr)
print(arr[3])


# sliding the elements
print(arr[0:3])

#Access the elements in 2D array
arr2 = np.array([[1,2,3],[2,3,4]])
print(arr2)
print(arr2[1,1])
print(arr2[0,:]) #First row with all columns
print(arr2[:,0]) #First column all rows

[1 2 3 4]
4
[1 2 3]
[[1 2 3]
 [2 3 4]]
3
[1 2 3]
[1 2]


In [36]:
l1 = np.arange(10,-10,-1)
print(l1)

[10  9  8  7  6  5  4  3  2  1  0 -1 -2 -3 -4 -5 -6 -7 -8 -9]


In [37]:
# mathematical operations

a = np.array([1,2,3])
b = np.array([4,5,6])
print(f'The sum of a and b is {a+b}')
print(f'The diff of a and b is {a-b}')
print(f'The product of a and b is {a*b}')
print(f'The division of a and b is {a/b}')

The sum of a and b is [5 7 9]
The diff of a and b is [-3 -3 -3]
The product of a and b is [ 4 10 18]
The division of a and b is [0.25 0.4  0.5 ]


In [43]:
#matrix multiplication
b1 = np.array([[1,2,3],[4,5,6]])
b2 = np.array([[5,5],[8,8],[1,8]])

#Dot product ---product = AB -- A m x n -- B n x p
c = np.dot(b1,b2)
print(c)

[[ 24  45]
 [ 66 108]]


In [44]:
print(b1)

[[1 2 3]
 [4 5 6]]


In [45]:
print(b2)

[[5 5]
 [8 8]
 [1 8]]
